
// Generated by Cadence Genus(TM) Synthesis Solution 21.12-s068_1
// Generated on: Jul 10 2026 14:14:33 -03 (Jul 10 2026 17:14:33 UTC)

// Verification Directory fv/i2c_driver 

module i2c_driver(clock, reset, data_p, enable, busy, scl, sda);
  input clock, reset, enable;
  input [7:0] data_p;
  output busy, scl;
  inout sda;
  wire clock, reset, enable;
  wire [7:0] data_p;
  wire busy, scl;
  wire sda;
  wire [7:0] shift_reg;
  wire [2:0] bit_cnt;
  wire [7:0] data_reg;
  wire [2:0] state;
  wire [1:0] phase;
  wire [7:0] clk_cnt;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, sda_low, start_req;
  HS65_GS_DFPRQX9 \shift_reg_reg[4] (.RN (n_102), .CP (clock), .D
       (n_97), .Q (shift_reg[4]));
  HS65_GS_DFPRQX9 \shift_reg_reg[5] (.RN (n_102), .CP (clock), .D
       (n_101), .Q (shift_reg[5]));
  HS65_GS_DFPRQX9 \shift_reg_reg[6] (.RN (n_102), .CP (clock), .D
       (n_100), .Q (shift_reg[6]));
  HS65_GS_DFPRQX9 \bit_cnt_reg[2] (.RN (n_102), .CP (clock), .D (n_96),
       .Q (bit_cnt[2]));
  HS65_GS_DFPRQX9 \bit_cnt_reg[1] (.RN (n_102), .CP (clock), .D (n_95),
       .Q (bit_cnt[1]));
  HS65_GS_AO212X4 g2099__2398(.A (shift_reg[4]), .B (n_99), .C
       (data_reg[5]), .D (n_98), .E (n_92), .Z (n_101));
  HS65_GS_AO212X4 g2100__5107(.A (shift_reg[5]), .B (n_99), .C
       (data_reg[6]), .D (n_98), .E (n_91), .Z (n_100));
  HS65_GS_AO212X4 g2101__6260(.A (shift_reg[3]), .B (n_99), .C
       (data_reg[4]), .D (n_98), .E (n_88), .Z (n_97));
  HS65_GS_DFPRQX9 \shift_reg_reg[0] (.RN (n_102), .CP (clock), .D
       (n_86), .Q (shift_reg[0]));
  HS65_GS_DFPRQX9 \shift_reg_reg[7] (.RN (n_102), .CP (clock), .D
       (n_87), .Q (shift_reg[7]));
  HS65_GS_DFPRQX9 \shift_reg_reg[3] (.RN (n_102), .CP (clock), .D
       (n_83), .Q (shift_reg[3]));
  HS65_GS_AO312X9 g2104__4319(.A (bit_cnt[2]), .B (n_79), .C (n_94), .D
       (bit_cnt[2]), .E (n_93), .F (n_80), .Z (n_96));
  HS65_GS_AO312X9 g2107__8428(.A (bit_cnt[1]), .B (n_77), .C (n_94), .D
       (bit_cnt[1]), .E (n_93), .F (n_78), .Z (n_95));
  HS65_GS_DFPRQX9 \shift_reg_reg[2] (.RN (n_102), .CP (clock), .D
       (n_82), .Q (shift_reg[2]));
  HS65_GS_DFPRQX9 \shift_reg_reg[1] (.RN (n_102), .CP (clock), .D
       (n_84), .Q (shift_reg[1]));
  HS65_GS_AO12X9 g2115__5526(.A (shift_reg[5]), .B (n_90), .C (n_89),
       .Z (n_92));
  HS65_GS_AO12X9 g2116__6783(.A (shift_reg[6]), .B (n_90), .C (n_89),
       .Z (n_91));
  HS65_GS_AO12X9 g2117__3680(.A (shift_reg[4]), .B (n_90), .C (n_89),
       .Z (n_88));
  HS65_GS_DFPRQX9 \state_reg[0] (.RN (n_102), .CP (clock), .D (n_81),
       .Q (state[0]));
  HS65_GS_AO222X4 g2108__1617(.A (n_99), .B (shift_reg[6]), .C
       (shift_reg[7]), .D (n_85), .E (data_reg[7]), .F (n_98), .Z
       (n_87));
  HS65_GS_AO22X9 g2111__2802(.A (shift_reg[0]), .B (n_85), .C
       (data_reg[0]), .D (n_98), .Z (n_86));
  HS65_GS_AO222X4 g2112__1705(.A (n_99), .B (shift_reg[0]), .C
       (shift_reg[1]), .D (n_85), .E (data_reg[1]), .F (n_98), .Z
       (n_84));
  HS65_GS_AO222X4 g2114__5122(.A (n_99), .B (shift_reg[2]), .C
       (shift_reg[3]), .D (n_85), .E (data_reg[3]), .F (n_98), .Z
       (n_83));
  HS65_GS_AO222X4 g2113__8246(.A (n_99), .B (shift_reg[1]), .C
       (shift_reg[2]), .D (n_85), .E (data_reg[2]), .F (n_98), .Z
       (n_82));
  HS65_GS_DFPRQX9 \state_reg[1] (.RN (n_102), .CP (clock), .D (n_74),
       .Q (state[1]));
  HS65_GS_DFPRQX9 \state_reg[2] (.RN (n_102), .CP (clock), .D (n_75),
       .Q (state[2]));
  HS65_GS_DFPRQX9 sda_low_reg(.RN (n_102), .CP (clock), .D (n_72), .Q
       (sda_low));
  HS65_GS_SDFPRQX9 \bit_cnt_reg[0] (.RN (n_102), .CP (clock), .D
       (n_99), .TI (n_93), .TE (bit_cnt[0]), .Q (bit_cnt[0]));
  HS65_GS_DFPRQX9 \phase_reg[1] (.RN (n_102), .CP (clock), .D (n_71),
       .Q (phase[1]));
  HS65_GS_AO312X4 g2103__7098(.A (bit_cnt[2]), .B (n_2), .C (n_99), .D
       (state[0]), .E (n_56), .F (n_89), .Z (n_81));
  HS65_GS_NOR3X4 g2130__6131(.A (bit_cnt[2]), .B (n_79), .C (n_76), .Z
       (n_80));
  HS65_GS_NOR3X4 g2131__1881(.A (bit_cnt[1]), .B (n_77), .C (n_76), .Z
       (n_78));
  HS65_GS_OAI211X4 g2110__5115(.A (n_59), .B (n_73), .C (n_7), .D
       (n_63), .Z (n_75));
  HS65_GS_OAI212X5 g2102__7482(.A (n_8), .B (n_73), .C (state[2]), .D
       (n_18), .E (n_66), .Z (n_74));
  HS65_GS_NAND3X5 g2148__4733(.A (n_68), .B (n_69), .C (n_67), .Z
       (n_90));
  HS65_GS_OAI311X5 g2109__6161(.A (state[0]), .B (n_20), .C (n_70), .D
       (n_51), .E (n_55), .Z (n_72));
  HS65_GS_DFPRQX9 \clk_cnt_reg[7] (.RN (n_102), .CP (clock), .D (n_64),
       .Q (clk_cnt[7]));
  HS65_GS_DFPRQX9 start_req_reg(.RN (n_102), .CP (clock), .D (n_65), .Q
       (start_req));
  HS65_GS_AO312X9 g2105__9315(.A (phase[1]), .B (n_61), .C (n_52), .D
       (phase[1]), .E (n_70), .F (n_53), .Z (n_71));
  HS65_GS_OAI212X5 g2127__9945(.A (n_69), .B (n_36), .C (start_req), .D
       (n_68), .E (n_67), .Z (n_85));
  HS65_GS_DFPRQX9 \phase_reg[0] (.RN (n_102), .CP (clock), .D (n_62),
       .Q (phase[0]));
  HS65_GS_AOI12X2 g2120__2883(.A (n_17), .B (n_73), .C (n_26), .Z
       (n_66));
  HS65_GS_IVX9 g2154(.A (n_99), .Z (n_76));
  HS65_GS_AO12X9 g2092__2346(.A (start_req), .B (n_49), .C (n_31), .Z
       (n_65));
  HS65_GS_AOI21X2 g2093__1666(.A (n_42), .B (n_35), .C (n_60), .Z
       (n_64));
  HS65_GS_IVX7 g2135(.A (n_98), .Z (n_63));
  HS65_GS_OAI32X5 g2106__7410(.A (phase[0]), .B (n_23), .C (n_70), .D
       (n_61), .E (n_60), .Z (n_62));
  HS65_GS_AND2X4 g2160__6417(.A (n_57), .B (n_58), .Z (n_67));
  HS65_GS_OAI212X5 g2147__5477(.A (n_69), .B (n_41), .C (n_59), .D
       (n_58), .E (n_57), .Z (n_93));
  HS65_GS_NOR3AX2 g2157__2398(.A (n_54), .B (state[0]), .C (n_56), .Z
       (n_99));
  HS65_GS_AOI32X5 g2119__5107(.A (sda_low), .B (n_50), .C (n_54), .D
       (sda_low), .E (n_70), .Z (n_55));
  HS65_GS_DFPRQX9 \clk_cnt_reg[4] (.RN (n_102), .CP (clock), .D (n_44),
       .Q (clk_cnt[4]));
  HS65_GS_SDFPSQX9 scl_r_reg(.SN (n_102), .CP (clock), .D (scl), .TI
       (n_38), .TE (n_60), .Q (scl));
  HS65_GS_DFPRQX9 \clk_cnt_reg[3] (.RN (n_102), .CP (clock), .D (n_47),
       .Q (clk_cnt[3]));
  HS65_GS_DFPRQX9 \clk_cnt_reg[1] (.RN (n_102), .CP (clock), .D (n_48),
       .Q (clk_cnt[1]));
  HS65_GS_NOR4ABX2 g2134__6260(.A (n_37), .B (n_52), .C (n_70), .D
       (n_61), .Z (n_53));
  HS65_GS_NAND4ABX3 g2133__4319(.A (n_70), .B (n_68), .C (state[0]), .D
       (n_50), .Z (n_51));
  HS65_GS_DFPRQX9 \clk_cnt_reg[6] (.RN (n_102), .CP (clock), .D (n_45),
       .Q (clk_cnt[6]));
  HS65_GS_DFPRQX9 \clk_cnt_reg[5] (.RN (n_102), .CP (clock), .D (n_46),
       .Q (clk_cnt[5]));
  HS65_GS_NOR2AX3 g2126__8428(.A (start_req), .B (n_49), .Z (n_89));
  HS65_GS_NOR2X6 g2141__5526(.A (n_3), .B (n_56), .Z (n_98));
  HS65_GS_IVX9 g2162(.A (n_56), .Z (n_73));
  HS65_GS_NOR2X6 g2163__6783(.A (n_13), .B (n_70), .Z (n_57));
  HS65_GS_NOR2AX3 g2097__3680(.A (n_9), .B (n_60), .Z (n_48));
  HS65_GS_CBI4I6X5 g2098__1617(.A (clk_cnt[3]), .B (n_15), .C (n_16),
       .D (n_60), .Z (n_47));
  HS65_GS_CBI4I6X5 g2095__2802(.A (clk_cnt[5]), .B (n_29), .C (n_30),
       .D (n_60), .Z (n_46));
  HS65_GS_NOR2X5 g2096__1705(.A (n_40), .B (n_60), .Z (n_45));
  HS65_GS_NOR2X5 g2094__5122(.A (n_22), .B (n_60), .Z (n_44));
  HS65_GS_SDFPRQX9 \data_reg_reg[2] (.RN (n_102), .CP (clock), .D
       (data_p[2]), .TI (data_reg[2]), .TE (n_43), .Q (data_reg[2]));
  HS65_GS_SDFPRQX9 \data_reg_reg[6] (.RN (n_102), .CP (clock), .D
       (data_p[6]), .TI (data_reg[6]), .TE (n_43), .Q (data_reg[6]));
  HS65_GS_SDFPRQX9 \data_reg_reg[3] (.RN (n_102), .CP (clock), .D
       (data_p[3]), .TI (data_reg[3]), .TE (n_43), .Q (data_reg[3]));
  HS65_GS_AOI21X2 g2132__8246(.A (clk_cnt[7]), .B (n_1), .C (n_32), .Z
       (n_42));
  HS65_GS_SDFPRQX9 \data_reg_reg[0] (.RN (n_102), .CP (clock), .D
       (data_p[0]), .TI (data_reg[0]), .TE (n_43), .Q (data_reg[0]));
  HS65_GS_SDFPRQX9 \data_reg_reg[5] (.RN (n_102), .CP (clock), .D
       (data_p[5]), .TI (data_reg[5]), .TE (n_43), .Q (data_reg[5]));
  HS65_GS_SDFPRQX9 \data_reg_reg[4] (.RN (n_102), .CP (clock), .D
       (data_p[4]), .TI (data_reg[4]), .TE (n_43), .Q (data_reg[4]));
  HS65_GS_SDFPRQX9 \data_reg_reg[1] (.RN (n_102), .CP (clock), .D
       (data_p[1]), .TI (data_reg[1]), .TE (n_43), .Q (data_reg[1]));
  HS65_GS_NAND2X7 g2145__7098(.A (n_41), .B (n_60), .Z (n_49));
  HS65_GS_SDFPRQX9 \data_reg_reg[7] (.RN (n_102), .CP (clock), .D
       (data_p[7]), .TI (data_reg[7]), .TE (n_43), .Q (data_reg[7]));
  HS65_GS_NAND2X7 g2165__6131(.A (n_69), .B (n_60), .Z (n_56));
  HS65_GS_IVX9 g2172(.A (n_60), .Z (n_70));
  HS65_GS_MUX21I1X6 g2121__1881(.D0 (n_39), .D1 (n_39), .S0
       (clk_cnt[6]), .Z (n_40));
  HS65_GS_NOR3AX4 g2174__5115(.A (n_33), .B (clk_cnt[2]), .C (n_34), .Z
       (n_60));
  HS65_GS_AO312X4 g2125__7482(.A (phase[0]), .B (n_37), .C (n_19), .D
       (n_61), .E (n_36), .F (n_27), .Z (n_38));
  HS65_GS_AOI21X2 g2129__4733(.A (clk_cnt[7]), .B (n_34), .C (n_33), .Z
       (n_35));
  HS65_GS_NOR3X4 g2144__6161(.A (clk_cnt[7]), .B (n_25), .C (n_34), .Z
       (n_32));
  HS65_GS_SDFPRQX9 \clk_cnt_reg[2] (.RN (n_102), .CP (clock), .D
       (n_10), .TI (n_11), .TE (clk_cnt[2]), .Q (clk_cnt[2]));
  HS65_GS_IVX9 g2122(.A (n_31), .Z (n_43));
  HS65_GS_NAND2X7 g2123__9315(.A (clk_cnt[5]), .B (n_29), .Z (n_30));
  HS65_GS_NOR2AX3 g2128__9945(.A (enable), .B (busy), .Z (n_31));
  HS65_GS_NAND2AX7 g2177__2883(.A (n_24), .B (clk_cnt[6]), .Z (n_34));
  HS65_GS_OAI31X4 g2143__2346(.A (phase[0]), .B (n_37), .C (n_26), .D
       (n_14), .Z (n_27));
  HS65_GS_NOR2X6 g2137__1666(.A (n_25), .B (n_24), .Z (n_39));
  HS65_GS_IVX7 g2153(.A (n_23), .Z (n_52));
  HS65_GS_MUX21I1X6 g2118__7410(.D0 (n_21), .D1 (n_21), .S0
       (clk_cnt[4]), .Z (n_22));
  HS65_GS_OA32X4 g2142__6417(.A (shift_reg[7]), .B (n_50), .C (n_36),
       .D (phase[1]), .E (n_19), .Z (n_20));
  HS65_GS_NOR3AX2 g2156__5477(.A (n_18), .B (n_17), .C (n_54), .Z
       (n_23));
  HS65_GS_NAND2X7 g2124__2398(.A (clk_cnt[3]), .B (n_15), .Z (n_16));
  HS65_GS_NAND2X7 g2178__5107(.A (clk_cnt[5]), .B (n_12), .Z (n_24));
  HS65_GS_AOI21X2 g2155__6260(.A (phase[0]), .B (n_13), .C (n_41), .Z
       (n_14));
  HS65_GS_NAND2X7 g2140__4319(.A (n_4), .B (n_12), .Z (n_29));
  HS65_GS_NAND2AX7 g2136__8428(.A (start_req), .B (n_41), .Z (busy));
  HS65_GS_IVX7 g2181(.A (n_10), .Z (n_11));
  HS65_GS_HA1X4 g2182__5526(.A0 (clk_cnt[1]), .B0 (n_5), .CO (n_10),
       .S0 (n_9));
  HS65_GS_NOR2AX3 g2179__6783(.A (clk_cnt[4]), .B (n_6), .Z (n_12));
  HS65_GS_OAI21X3 g2183__3680(.A (state[2]), .B (n_8), .C (n_7), .Z
       (n_54));
  HS65_GS_NOR2X6 g2168__1617(.A (state[0]), .B (n_68), .Z (n_41));
  HS65_GS_NOR2X6 g2138__2802(.A (n_6), .B (n_25), .Z (n_21));
  HS65_GS_NAND2X7 g2139__1705(.A (n_5), .B (n_4), .Z (n_15));
  HS65_GS_NAND2X7 g2146__5122(.A (n_18), .B (n_7), .Z (n_94));
  HS65_GS_NOR2X6 g2170__8246(.A (state[0]), .B (n_19), .Z (n_13));
  HS65_GS_IVX9 g2169(.A (n_68), .Z (n_36));
  HS65_GS_NOR2X6 g2159__7098(.A (n_59), .B (n_3), .Z (n_26));
  HS65_GS_IVX9 g2161(.A (n_58), .Z (n_17));
  HS65_GS_NAND2X7 g2180__6131(.A (n_5), .B (clk_cnt[3]), .Z (n_6));
  HS65_GS_DFPRQNX9 \clk_cnt_reg[0] (.RN (n_102), .CP (clock), .D
       (clk_cnt[0]), .QN (clk_cnt[0]));
  HS65_GS_NAND2X7 g2184__1881(.A (state[2]), .B (n_8), .Z (n_7));
  HS65_GS_NOR2X6 g2173__5115(.A (n_61), .B (n_37), .Z (n_69));
  HS65_GS_NAND2X7 g2171__7482(.A (n_8), .B (n_59), .Z (n_68));
  HS65_GS_IVX7 g2149(.A (n_79), .Z (n_2));
  HS65_GS_IVX9 g2150(.A (n_25), .Z (n_4));
  HS65_GS_NAND2X7 g2167__4733(.A (state[1]), .B (n_0), .Z (n_18));
  HS65_GS_NAND2X7 g2158__6161(.A (n_61), .B (n_37), .Z (n_50));
  HS65_GS_NAND2X7 g2164__9315(.A (state[0]), .B (n_8), .Z (n_58));
  HS65_GS_ITHX10 sda_tri__9945(.A (1'b1), .E (sda_low), .Z (sda));
  HS65_GS_NOR2AX3 g2175__2883(.A (clk_cnt[7]), .B (clk_cnt[1]), .Z
       (n_33));
  HS65_GS_NAND2X7 g2176__2346(.A (state[1]), .B (state[2]), .Z (n_19));
  HS65_GS_NAND2X7 g2166__1666(.A (state[0]), .B (state[1]), .Z (n_3));
  HS65_GS_NAND2X7 g2151__7410(.A (bit_cnt[0]), .B (bit_cnt[1]), .Z
       (n_79));
  HS65_GS_NAND2X7 g2152__6417(.A (clk_cnt[1]), .B (clk_cnt[2]), .Z
       (n_25));
  HS65_GS_IVX9 g2191(.A (clk_cnt[0]), .Z (n_5));
  HS65_GS_IVX9 g2185(.A (state[2]), .Z (n_59));
  HS65_GS_IVX9 g2186(.A (state[1]), .Z (n_8));
  HS65_GS_IVX2 g2188(.A (reset), .Z (n_102));
  HS65_GS_IVX4 g2190(.A (clk_cnt[2]), .Z (n_1));
  HS65_GS_IVX7 g2193(.A (state[0]), .Z (n_0));
  HS65_GS_IVX9 g2189(.A (bit_cnt[0]), .Z (n_77));
  HS65_GS_IVX9 g2192(.A (phase[1]), .Z (n_37));
  HS65_GS_IVX9 g2187(.A (phase[0]), .Z (n_61));
endmodule

